SEED_TOOLS = [
    # --- recon / osint ------------------------------------------------------
    ("nmap", "recon", "Network/port scanner and service fingerprinter", "apt install nmap", "nmap"),
    ("masscan", "recon", "Internet-scale TCP port scanner", "apt install masscan", "masscan"),
    ("rustscan", "recon", "Ultra-fast port scanner (feeds nmap)", "cargo install rustscan", "rustscan"),
    ("naabu", "recon", "Fast SYN/CONNECT port scanner (ProjectDiscovery)", "go install .../naabu", "naabu"),
    ("amass", "recon", "In-depth subdomain enumeration/attack surface", "apt install amass", "amass"),
    ("subfinder", "recon", "Passive subdomain discovery", "go install .../subfinder", "subfinder"),
    ("assetfinder", "recon", "Find domains/subdomains", "go install .../assetfinder", "assetfinder"),
    ("dnsx", "recon", "Fast DNS toolkit", "go install .../dnsx", "dnsx"),
    ("dnsenum", "recon", "DNS enumeration", "apt install dnsenum", "dnsenum"),
    ("dnsrecon", "recon", "DNS recon and record enumeration", "apt install dnsrecon", "dnsrecon"),
    ("fierce", "recon", "DNS reconnaissance / zone transfer", "pip install fierce", "fierce"),
    ("theHarvester", "osint", "Emails/subdomains/names from public sources", "apt install theharvester", "theHarvester"),
    ("recon-ng", "osint", "Full-featured web recon framework", "apt install recon-ng", "recon-ng"),
    ("spiderfoot", "osint", "Automated OSINT collection", "pip install spiderfoot", "sf"),
    ("shodan", "osint", "Shodan CLI (device search engine)", "pip install shodan", "shodan"),
    ("maltego", "osint", "Graphical link-analysis / OSINT", "apt install maltego", "maltego"),
    ("sherlock", "osint", "Hunt usernames across social networks", "pip install sherlock-project", "sherlock"),
    ("holehe", "osint", "Check if an email is used on sites", "pip install holehe", "holehe"),
    ("gitleaks", "osint", "Find secrets in git repos", "brew install gitleaks", "gitleaks"),
    ("trufflehog", "osint", "Find leaked credentials in code", "pip install trufflehog", "trufflehog"),

    # --- web ----------------------------------------------------------------
    ("nikto", "web", "Web server vulnerability scanner", "apt install nikto", "nikto"),
    ("gobuster", "web", "Directory/DNS/vhost brute-forcer", "apt install gobuster", "gobuster"),
    ("ffuf", "web", "Fast web fuzzer", "go install .../ffuf", "ffuf"),
    ("feroxbuster", "web", "Recursive content discovery", "apt install feroxbuster", "feroxbuster"),
    ("dirsearch", "web", "Web path brute-forcer", "pip install dirsearch", "dirsearch"),
    ("wfuzz", "web", "Web application fuzzer", "pip install wfuzz", "wfuzz"),
    ("sqlmap", "web", "Automatic SQL injection & DB takeover", "apt install sqlmap", "sqlmap"),
    ("wpscan", "web", "WordPress vulnerability scanner", "gem install wpscan", "wpscan"),
    ("nuclei", "web", "Template-based vuln scanner (~9k templates)", "go install .../nuclei", "nuclei"),
    ("httpx", "web", "Fast HTTP probing/toolkit", "go install .../httpx", "httpx"),
    ("katana", "web", "Next-gen crawling/spider", "go install .../katana", "katana"),
    ("gau", "web", "Fetch known URLs (wayback/otx)", "go install .../gau", "gau"),
    ("waybackurls", "web", "Pull URLs from the Wayback Machine", "go install .../waybackurls", "waybackurls"),
    ("arjun", "web", "HTTP parameter discovery", "pip install arjun", "arjun"),
    ("dalfox", "web", "XSS scanner/parameter analyzer", "go install .../dalfox", "dalfox"),
    ("xsstrike", "web", "Advanced XSS detection", "git clone XSStrike", "xsstrike"),
    ("commix", "web", "Automated command-injection", "apt install commix", "commix"),
    ("whatweb", "web", "Web technology fingerprinter", "apt install whatweb", "whatweb"),
    ("wafw00f", "web", "Identify/fingerprint WAFs", "pip install wafw00f", "wafw00f"),
    ("burpsuite", "web", "Web proxy / testing platform", "apt install burpsuite", "burpsuite"),
    ("zaproxy", "web", "OWASP ZAP web proxy/scanner", "apt install zaproxy", "zaproxy"),
    ("jwt_tool", "web", "Test/forge JSON Web Tokens", "git clone jwt_tool", None),

    # --- exploitation / frameworks -----------------------------------------
    ("metasploit", "exploit", "Exploitation framework (~2,300 exploits)", "apt install metasploit-framework", "msfconsole"),
    ("searchsploit", "exploit", "Offline Exploit-DB search (~45k exploits)", "apt install exploitdb", "searchsploit"),
    ("beef-xss", "exploit", "Browser exploitation framework", "apt install beef-xss", "beef-xss"),
    ("routersploit", "exploit", "Exploitation framework for embedded devices", "pip install routersploit", "rsf"),
    ("setoolkit", "exploit", "Social-engineering toolkit", "apt install set", "setoolkit"),
    ("evil-winrm", "exploit", "WinRM shell for pentesting", "gem install evil-winrm", "evil-winrm"),
    ("impacket", "exploit", "Python network-protocol toolkit (SMB/etc.)", "pip install impacket", None),
    ("crackmapexec", "exploit", "Swiss-army knife for AD/networks", "pipx install crackmapexec", "crackmapexec"),
    ("netexec", "exploit", "Maintained CME successor (nxc)", "pipx install netexec", "nxc"),

    # --- passwords / cracking ----------------------------------------------
    ("john", "passwords", "John the Ripper password cracker", "apt install john", "john"),
    ("hashcat", "passwords", "GPU-accelerated hash cracker", "apt install hashcat", "hashcat"),
    ("hydra", "passwords", "Network login brute-forcer", "apt install hydra", "hydra"),
    ("medusa", "passwords", "Parallel network login brute-forcer", "apt install medusa", "medusa"),
    ("ncrack", "passwords", "High-speed network auth cracker", "apt install ncrack", "ncrack"),
    ("patator", "passwords", "Multi-purpose brute-forcer", "pip install patator", "patator"),
    ("hashid", "passwords", "Identify hash types", "pip install hashid", "hashid"),
    ("hash-identifier", "passwords", "Identify hash types", "apt install hash-identifier", "hash-identifier"),
    ("cewl", "passwords", "Custom wordlist generator from a site", "apt install cewl", "cewl"),
    ("crunch", "passwords", "Wordlist generator by pattern", "apt install crunch", "crunch"),
    ("cupp", "passwords", "Common user password profiler", "git clone cupp", None),

    # --- network / sniffing / mitm -----------------------------------------
    ("wireshark", "network", "Network protocol analyzer (GUI)", "apt install wireshark", "wireshark"),
    ("tshark", "network", "Wireshark CLI", "apt install tshark", "tshark"),
    ("tcpdump", "network", "CLI packet capture", "apt install tcpdump", "tcpdump"),
    ("ettercap", "network", "MITM / ARP poisoning suite", "apt install ettercap-graphical", "ettercap"),
    ("bettercap", "network", "Modern MITM/network attack framework", "apt install bettercap", "bettercap"),
    ("responder", "network", "LLMNR/NBT-NS/MDNS poisoner", "apt install responder", "responder"),
    ("mitmproxy", "network", "Interactive HTTPS proxy", "pip install mitmproxy", "mitmproxy"),
    ("scapy", "network", "Packet crafting/manipulation library", "pip install scapy", None),
    ("netcat", "network", "TCP/UDP swiss-army knife", "apt install netcat-traditional", "nc"),
    ("socat", "network", "Multipurpose relay", "apt install socat", "socat"),
    ("proxychains", "network", "Force TCP through proxies", "apt install proxychains4", "proxychains4"),

    # --- wireless -----------------------------------------------------------
    ("aircrack-ng", "wireless", "WiFi cracking suite", "apt install aircrack-ng", "aircrack-ng"),
    ("wifite", "wireless", "Automated wireless attacks", "apt install wifite", "wifite"),
    ("kismet", "wireless", "Wireless sniffer/IDS", "apt install kismet", "kismet"),
    ("reaver", "wireless", "WPS PIN brute-force", "apt install reaver", "reaver"),
    ("bully", "wireless", "WPS brute-force", "apt install bully", "bully"),
    ("hcxdumptool", "wireless", "Capture WPA PMKID", "apt install hcxdumptool", "hcxdumptool"),
    ("fluxion", "wireless", "Evil-twin / handshake capture", "git clone fluxion", None),

    # --- reversing / exploitdev / forensics --------------------------------
    ("ghidra", "reversing", "NSA reverse-engineering suite", "apt install ghidra", "ghidra"),
    ("radare2", "reversing", "Reverse-engineering framework", "apt install radare2", "r2"),
    ("rizin", "reversing", "radare2 fork RE framework", "apt install rizin", "rizin"),
    ("gdb", "reversing", "GNU debugger (+pwndbg/gef)", "apt install gdb", "gdb"),
    ("binwalk", "reversing", "Firmware analysis/extraction", "apt install binwalk", "binwalk"),
    ("pwntools", "reversing", "CTF/exploit-dev Python library", "pip install pwntools", None),
    ("ropgadget", "reversing", "Find ROP gadgets", "pip install ropgadget", "ROPgadget"),
    ("one_gadget", "reversing", "Find one-shot RCE gadgets in libc", "gem install one_gadget", "one_gadget"),
    ("volatility3", "forensics", "Memory forensics framework", "pip install volatility3", "vol"),
    ("autopsy", "forensics", "Digital forensics platform", "apt install autopsy", "autopsy"),
    ("foremost", "forensics", "File carving/recovery", "apt install foremost", "foremost"),
    ("exiftool", "forensics", "Read/write file metadata", "apt install libimage-exiftool-perl", "exiftool"),
    ("steghide", "stego", "Hide/extract data in images/audio", "apt install steghide", "steghide"),
    ("stegseek", "stego", "Fast steghide cracker", "apt install stegseek", "stegseek"),
    ("zsteg", "stego", "Detect stego in PNG/BMP", "gem install zsteg", "zsteg"),

    # --- post-exploitation / AD / privesc ----------------------------------
    ("bloodhound", "postexp", "Active Directory attack-path mapping", "pip install bloodhound", "bloodhound-python"),
    ("mimikatz", "postexp", "Windows credential extraction", "download release", "mimikatz"),
    ("linpeas", "postexp", "Linux privilege-escalation enum", "git clone PEASS-ng", None),
    ("winpeas", "postexp", "Windows privilege-escalation enum", "git clone PEASS-ng", None),
    ("linenum", "postexp", "Linux enumeration script", "git clone LinEnum", None),
    ("pspy", "postexp", "Snoop processes without root", "download release", "pspy"),
    ("chisel", "postexp", "TCP/UDP tunnel over HTTP", "go install .../chisel", "chisel"),
    ("ligolo-ng", "postexp", "Tunneling/pivoting tool", "download release", "ligolo"),

    # --- c2 -----------------------------------------------------------------
    ("sliver", "c2", "Cross-platform C2 framework", "curl sliver.sh | sh", "sliver-server"),
    ("covenant", "c2", ".NET C2 framework", "docker covenant", None),
    ("havoc", "c2", "Modern C2 framework", "git clone Havoc", None),
    ("mythic", "c2", "Collaborative multiplayer C2", "git clone Mythic", None),
    ("empire", "c2", "PowerShell/Python post-exploitation C2", "apt install powershell-empire", "empire"),

    # --- cloud / container --------------------------------------------------
    ("prowler", "cloud", "AWS/Azure/GCP security assessment", "pip install prowler", "prowler"),
    ("scoutsuite", "cloud", "Multi-cloud security auditing", "pip install scoutsuite", "scout"),
    ("pacu", "cloud", "AWS exploitation framework", "pip install pacu", "pacu"),
    ("trivy", "cloud", "Container/IaC vulnerability scanner", "apt install trivy", "trivy"),
    ("kube-hunter", "cloud", "Kubernetes pen-test tool", "pip install kube-hunter", "kube-hunter"),

    # --- mobile -------------------------------------------------------------
    ("mobsf", "mobile", "Mobile app security framework", "docker mobsf", None),
    ("apktool", "mobile", "Reverse-engineer APKs", "apt install apktool", "apktool"),
    ("frida", "mobile", "Dynamic instrumentation toolkit", "pip install frida-tools", "frida"),
    ("objection", "mobile", "Runtime mobile exploration (Frida)", "pip install objection", "objection"),
    ("jadx", "mobile", "Dex to Java decompiler", "apt install jadx", "jadx"),

    # --- fuzzing ------------------------------------------------------------
    ("afl++", "fuzzing", "Coverage-guided fuzzer", "apt install aflplusplus", "afl-fuzz"),
    ("boofuzz", "fuzzing", "Network protocol fuzzing framework", "pip install boofuzz", None),
    ("radamsa", "fuzzing", "Mutation-based blackbox fuzzer", "apt install radamsa", "radamsa"),

    # --- misc / utility -----------------------------------------------------
    ("cyberchef", "misc", "The 'cyber swiss-army knife' (web)", "web/electron", None),
    ("seclists", "misc", "Massive collection of security wordlists", "apt install seclists", None),
    ("payloadsallthethings", "misc", "Huge payload/technique reference", "git clone PayloadsAllTheThings", None),
    ("gtfobins", "misc", "Unix binaries for bypassing restrictions (ref)", "web reference", None),
    ("lolbas", "misc", "Living-off-the-land Windows binaries (ref)", "web reference", None),

    # --- curated additions (the "100 tools" list) ---------------------------
    ("censys", "osint", "Internet asset search engine (CLI/API)", "pip install censys", "censys"),
    ("photon", "osint", "Fast OSINT web crawler (urls, secrets, accounts)", "git clone s0md3v/Photon", None),
    ("bbot", "osint", "Modular OSINT/recon/scanning framework", "pipx install bbot", "bbot"),
    ("reconftw", "recon", "Automated recon for bug bounty & pentest", "git clone six2dez/reconftw", "reconftw"),
    ("foca", "osint", "Document metadata & hidden-info analysis (Windows)", "download (ElevenPaths)", None),
    ("angryip", "recon", "Fast GUI IP/port scanner", "download angryip.org", "ipscan"),
    ("ladon", "recon", "Large-scale scanner & asset discovery", "git clone k8gege/Ladon", None),
    ("openvpn", "network", "Encrypted VPN tunneling", "apt install openvpn", "openvpn"),
    ("softether", "network", "Multi-protocol VPN server/client", "download softether.org", None),
    ("caido", "web", "Rust-based lightweight Burp alternative", "download caido.io", "caido"),
    ("kiterunner", "web", "API endpoint content discovery", "download assetnote/kiterunner", "kr"),
    ("postman", "web", "API development & endpoint testing client", "download postman.com", None),
    ("nessus", "web", "Commercial vulnerability scanner (Tenable)", "download tenable.com", None),
    ("openvas", "web", "Open-source vuln scanner (Greenbone GVM)", "apt install openvas", "gvm-cli"),
    ("acunetix", "web", "Commercial web vulnerability scanner", "download acunetix.com", None),
    ("qualys", "cloud", "Cloud security & compliance platform (Qualys)", "SaaS (qualys.com)", None),
    ("nexpose", "web", "Vulnerability scanner (Rapid7 InsightVM)", "download rapid7.com", None),
    ("cobaltstrike", "c2", "Commercial adversary-simulation C2", "licensed (fortra.com)", None),
    ("canvas", "exploit", "Commercial exploitation framework (Immunity)", "licensed (immunityinc.com)", None),
    ("bruteratel", "c2", "Commercial red-team C2 (Brute Ratel C4)", "licensed (bruteratel.com)", None),
    ("cain", "passwords", "Legacy Windows password recovery & sniffer", "download (legacy)", None),
    ("mentalist", "passwords", "GUI manual wordlist generator", "git clone sc0tfree/mentalist", None),
    ("fern-wifi-cracker", "wireless", "GUI wireless security auditing", "apt install fern-wifi-cracker", "fern-wifi-cracker"),
    ("wifiphisher", "wireless", "Rogue-AP phishing / evil-twin framework", "apt install wifiphisher", "wifiphisher"),
    ("powerview", "postexp", "PowerShell AD situational awareness (PowerSploit)", "git clone PowerShellMafia/PowerSploit", None),
    ("certipy", "postexp", "AD Certificate Services (AD CS) enum/abuse", "pipx install certipy-ad", "certipy"),
    ("rubeus", "postexp", "C# raw Kerberos interaction & abuse", "compile GhostPack/Rubeus", None),
    ("sharphound", "postexp", "BloodHound C# data collector", "download BloodHound release", None),
    ("kerbrute", "postexp", "Kerberos brute-force, user enum & spray", "go install ropnop/kerbrute", "kerbrute"),
    ("petitpotam", "postexp", "Coerce Windows auth via MS-EFSRPC", "git clone topotam/PetitPotam", None),
    ("checkov", "cloud", "IaC static analysis (Terraform/CFN/K8s)", "pip install checkov", "checkov"),
    ("cloudsploit", "cloud", "Cloud security posture management", "git clone aquasecurity/cloudsploit", None),
    ("idapro", "reversing", "Commercial disassembler & debugger (IDA Pro)", "licensed (hex-rays.com)", None),
    ("x64dbg", "reversing", "Open-source x64/x32 Windows debugger", "download x64dbg.com", None),
    ("cutter", "reversing", "GUI for the radare2/rizin RE framework", "apt install cutter", "cutter"),
    ("yara", "forensics", "Pattern-matching engine for malware research", "apt install yara", "yara"),
    ("pe-bear", "reversing", "PE header parsing / reversing tool", "download hasherezade/pe-bear", None),

    # --- v0.2 expansion: recon / osint -------------------------------------
    ("massdns", "recon", "High-performance DNS stub resolver for bulk lookups", "git clone blechschmidt/massdns", "massdns"),
    ("puredns", "recon", "Fast subdomain bruteforce + resolver wrapper", "go install .../puredns", "puredns"),
    ("shuffledns", "recon", "massdns wrapper for subdomain enumeration", "go install .../shuffledns", "shuffledns"),
    ("gospider", "recon", "Fast web spider written in Go", "go install jaeles-project/gospider", "gospider"),
    ("hakrawler", "recon", "Fast web crawler for endpoint discovery", "go install hakluke/hakrawler", "hakrawler"),
    ("gowitness", "recon", "Headless-Chrome web screenshot utility", "go install sensepost/gowitness", "gowitness"),
    ("aquatone", "recon", "Visual inspection of websites across many hosts", "go install .../aquatone", "aquatone"),
    ("eyewitness", "recon", "Screenshot sites, fingerprint services", "apt install eyewitness", "eyewitness"),
    ("cero", "recon", "Scrape domain names from TLS certificates", "go install glebarez/cero", "cero"),
    ("uncover", "recon", "Find exposed hosts via Shodan/Censys/Fofa", "go install .../uncover", "uncover"),
    ("metabigor", "osint", "OSINT with no API keys (ASN/IP/org)", "go install j3ssie/metabigor", "metabigor"),
    ("dnstwist", "osint", "Find typosquat / phishing lookalike domains", "pip install dnstwist", "dnstwist"),
    ("h8mail", "osint", "Email breach hunting and credential lookup", "pip install h8mail", "h8mail"),
    ("maigret", "osint", "Collect a dossier on a username across sites", "pip install maigret", "maigret"),
    ("phoneinfoga", "osint", "OSINT framework for phone numbers", "download sundowndev/phoneinfoga", "phoneinfoga"),
    ("gitdorker", "osint", "GitHub dorking to surface leaked secrets", "git clone obheda12/GitDorker", None),
    ("waymore", "osint", "Pull URLs from Wayback/CommonCrawl/URLScan", "pip install waymore", "waymore"),

    # --- v0.2 expansion: web / api -----------------------------------------
    ("x8", "web", "Hidden HTTP parameter discovery (Rust)", "cargo install x8", "x8"),
    ("paramspider", "web", "Mine parameters from web archives", "pip install paramspider", "paramspider"),
    ("crlfuzz", "web", "Fast CRLF-injection scanner", "go install dwisiswant0/crlfuzz", "crlfuzz"),
    ("gf", "web", "grep wrapper of curated vuln-pattern rules", "go install tomnomnom/gf", "gf"),
    ("interactsh", "web", "Out-of-band interaction (OAST) client", "go install .../interactsh-client", "interactsh-client"),
    ("smuggler", "web", "HTTP request-smuggling detection", "git clone defparam/smuggler", None),
    ("graphqlmap", "web", "Interact with and exploit GraphQL endpoints", "git clone swisskyrepo/GraphQLmap", None),
    ("clairvoyance", "web", "Recover a GraphQL schema without introspection", "pip install clairvoyance", "clairvoyance"),
    ("tplmap", "web", "Automatic server-side template injection & RCE", "git clone epinna/tplmap", None),
    ("nosqlmap", "web", "Automated NoSQL injection and DB takeover", "git clone codingo/NoSQLMap", None),
    ("semgrep", "web", "Fast multi-language static analysis (SAST)", "pip install semgrep", "semgrep"),
    ("bandit", "web", "Security linter for Python source", "pip install bandit", "bandit"),

    # --- v0.2 expansion: AD / smb / postexp --------------------------------
    ("enum4linux-ng", "smb", "Next-gen SMB/AD enumeration", "pip install enum4linux-ng", "enum4linux-ng"),
    ("smbclient", "smb", "Interactive SMB share client", "apt install smbclient", "smbclient"),
    ("nbtscan", "smb", "NetBIOS name scanner", "apt install nbtscan", "nbtscan"),
    ("coercer", "postexp", "Coerce Windows auth (multi-method)", "pipx install coercer", "coercer"),
    ("adidnsdump", "postexp", "Dump AD-integrated DNS over LDAP", "pip install adidnsdump", "adidnsdump"),
    ("ldapdomaindump", "postexp", "Dump AD info over LDAP", "pip install ldapdomaindump", "ldapdomaindump"),
    ("pingcastle", "postexp", "AD security audit and risk report", "download pingcastle.com", "PingCastle"),
    ("adalanche", "postexp", "AD ACL attack-path visualizer", "download lkarlslund/adalanche", "adalanche"),
    ("donpapi", "postexp", "Dump DPAPI secrets across a domain", "pipx install donpapi", "donpapi"),
    ("nanodump", "postexp", "Create an LSASS minidump stealthily", "compile nanodump", None),

    # --- v0.2 expansion: c2 -------------------------------------------------
    ("villain", "c2", "Backdoor and session-management C2", "git clone t3l3machus/Villain", None),
    ("merlin", "c2", "Cross-platform HTTP/2 C2 framework", "download Ne0nd0g/merlin", "merlinServer"),
    ("nimplant", "c2", "Lightweight Nim/Python C2", "git clone chvancooten/NimPlant", None),
    ("pupy", "c2", "Cross-platform Python C2 / RAT", "git clone n1nj4sec/pupy", None),

    # --- v0.2 expansion: forensics / reversing -----------------------------
    ("sleuthkit", "forensics", "Filesystem forensic analysis toolset", "apt install sleuthkit", "fls"),
    ("bulk-extractor", "forensics", "Extract emails/CCs/features from disk images", "apt install bulk-extractor", "bulk_extractor"),
    ("plaso", "forensics", "Super-timeline generation (log2timeline)", "pip install plaso", "log2timeline.py"),
    ("velociraptor", "forensics", "Endpoint DFIR and threat hunting", "download velocidex/velociraptor", "velociraptor"),
    ("regripper", "forensics", "Windows registry analysis", "apt install regripper", "rip.pl"),
    ("chainsaw", "forensics", "Fast Windows event-log hunting (Sigma)", "download WithSecure/chainsaw", "chainsaw"),
    ("hayabusa", "forensics", "Windows event-log timeline & threat hunt", "download Yamato-Security/hayabusa", "hayabusa"),
    ("capa", "reversing", "Identify capabilities in executables", "pip install flare-capa", "capa"),
    ("floss", "reversing", "Extract obfuscated strings from malware", "pip install flare-floss", "floss"),
    ("die", "reversing", "Detect It Easy - packer/compiler detection", "download horsicq/DIE", "diec"),
    ("angr", "reversing", "Binary analysis and symbolic execution", "pip install angr", None),

    # --- v0.2 expansion: detection / blue-team -----------------------------
    ("sigma-cli", "detection", "Convert Sigma rules to SIEM queries", "pip install sigma-cli", "sigma"),
    ("suricata", "detection", "High-performance network IDS/IPS", "apt install suricata", "suricata"),
    ("zeek", "detection", "Network security monitor (formerly Bro)", "apt install zeek", "zeek"),
    ("snort", "detection", "Network intrusion detection/prevention", "apt install snort", "snort"),
    ("wazuh", "detection", "Open-source XDR / SIEM platform", "download wazuh.com", None),

    # --- v0.2 expansion: mobile / containers -------------------------------
    ("drozer", "mobile", "Android security assessment framework", "pip install drozer", "drozer"),
    ("apkleaks", "mobile", "Scan APKs for URIs/endpoints/secrets", "pip install apkleaks", "apkleaks"),
    ("mobsfscan", "mobile", "Static analysis for mobile app code", "pip install mobsfscan", "mobsfscan"),
    ("grype", "cloud", "Container/filesystem vulnerability scanner", "brew install grype", "grype"),
    ("syft", "cloud", "Generate SBOMs from images/filesystems", "brew install syft", "syft"),
    ("tfsec", "cloud", "Terraform static security scanner", "brew install tfsec", "tfsec"),
    ("kubeaudit", "cloud", "Audit Kubernetes clusters for risks", "go install .../kubeaudit", "kubeaudit"),
    ("kube-bench", "cloud", "CIS Kubernetes benchmark checks", "download aquasecurity/kube-bench", "kube-bench"),
    ("dockle", "cloud", "Container-image security linter", "brew install dockle", "dockle"),
]
